### PR TITLE
Don't prevent default if opening outbound link in a new tab.

### LINKED ISSUE #929: User Download PDF link for HP action fails on ipad 3
It works fine from the admin UI on the same device, however.

### PR DESCRIPTION
**Pull request by toolness**
This (hopefully) fixes #929 by not preventing default link-click behavior for outbound links that will open in a new tab/window.  It also sends the GA link click event even if a modifier key is pressed (so we're basically assuming that if the user clicks a link with a modifier key, it's for the purpose of opening it in a new tab, or viewing it in some other way).

### CODE REVIEW

File: frontend/lib/tests/rtl-pal.tsx [hunk 1]
```diff
@@ -54,22 +54,22 @@ export default class ReactTestingLibraryPal {
 
   /** Click anything with the given text and selector. */
   click(matcher: RegExp|string, selector: string) {
-    rt.fireEvent.click(this.getByTextAndSelector(matcher, selector));
+    return rt.fireEvent.click(this.getByTextAndSelector(matcher, selector));
```
Comment (toolness) [inline frontend/lib/tests/rtl-pal.tsx]: RTL's `fireEvent` actually returns the result of the underlying [`dispatchEvent()`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) call, which is useful to detect whether a handler called `event.preventDefault()`.  We need this for our tests, so I exposed the return value on `ReactTestingLibraryPal`'s relevant methods.

**Comment by toolness** [comment]
[ch930]

File: frontend/lib/google-analytics.tsx [hunk 2]
```diff
@@ -188,30 +189,24 @@ export function trackPageView(pathname: string) {
...
 export function handleOutboundLinkClick(e: MouseEvent<HTMLAnchorElement>) {
   // If any modifier key is pressed, odds are that the user is trying to
   // invoke some browser-specific behavior to e.g. open the link in a
   // new window or tab. We don't want to break that.
   const isModifierPressed = e.altKey || e.ctrlKey || e.metaKey || e.shiftKey;
+  const { href, target } = e.currentTarget;
 
-  if (!isModifierPressed) {
-    const { href, target } = e.currentTarget;
+  const willOpenInNewWindow = target && target !== window.name;
```
Comment (toolness) [inline frontend/lib/google-analytics.tsx]: I've verified in Chrome that if our current window was opened via `target="_blank"`, its `window.name` is just the empty string, _not_ `"_blank"`, so this logic _should_ work, um, unless different browsers have different behaviors here.
